- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
    - mc
    - tmux
    - tree
    - git
    - curl
    - vim
    - unzip
    - xvfb
    - firefox=68.0.2
    - ubuntu-desktop      # gnome desktop

