Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder "src/", "/home/vagrant/src"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = 3
  end  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    # Download Mesos
    sudo apt-get install -y openjdk-8-jdk
    sudo apt-get -y install build-essential python-dev python-six python-virtualenv libcurl4-nss-dev libsasl2-dev libsasl2-modules maven libapr1-dev libsvn-dev zlib1g-dev
    sudo apt-get install -y autoconf libtool
    
    wget http://www.apache.org/dist/mesos/1.9.0/mesos-1.9.0.tar.gz
    tar -zxf mesos-1.9.0.tar.gz
    cd mesos-1.9.0
    mkdir build
    cd build
    ../configure
    make
    make check
    make install
  
  SHELL
end
