BOX_IMAGE  = "bento/ubuntu-18.04"
NODE_COUNT = 1

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "vm.node#{i}.lab" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 9}", virtualbox__intnet: "mynetwork"
    end
  end
  config.vm.provision "file", source: "~/EXP/termgraph/data/.", destination: "$HOME/"
  config.vm.provision "file", source: "~/.config/fish/.", destination: "$HOME/.config/"
  config.vm.provision "docker", images: ["nginx"]
  # Runs as /root
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y tree ranger fish vim
    apt-get -y install python3-pip
    pip3 install termgraph
    curl -L https://get.oh-my.fish | fish
  SHELL
end