# my global config
global:
  scrape_interval:     2s
  evaluation_interval: 2s
  external_labels:
      monitor: 'vagrant-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['localhost:9100']