BOX_IMAGE  = "bento/ubuntu-18.04"
NODE_COUNT = 1

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "vm.node#{i}.lab" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 9}", virtualbox__intnet: "mynetwork"
    end
  end
  config.vm.provision "file", source: "./prometheus.yml", destination: "/etc/prometheus/prometheus.yml"
  # config.vm.provision "file", source: "~/.config/fish/.", destination: "$HOME/.config/"
  # config.vm.provision "docker", images: ["nginx"]
  
  # Runs as /root
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y tree ranger fish vim
    apt-get -y install python3-pip
    wget https://github.com/prometheus/prometheus/releases/download/v2.13.1/prometheus-2.13.1.linux-amd64.tar.gz
    echo "1091754f40e31c4598d0f4eb3cf0d4daafb307009422b193f817bba5ae0da6fd  prometheus-2.13.1.linux-amd64.tar.gz" | sha256sum --check
    tar -xvzf prometheus-2.13.1.linux-amd64.tar.gz
    cd prometheus-2.13.1.linux-amd64
    
    apt install prometheus # installs both prometheus and node_exporter
    # service maintained by systemd
  SHELL
end