#!/usr/bin/python3

# NAME      : Analyze
# AUTHOR    : Avi Mehenwal
# DATE      : 4th October 2019
# PURPOSE   : Analyze the traffic generated by LB

import sys
from termcolor import colored, cprint

seen = dict()
with sys.stdin as FD:   
    for index, line in enumerate(FD):
        if line not in seen.keys():
            seen[line] = 1
        else:
            count = seen[line]
            seen[line] = count + 1
cprint("Participating Nodes : {}".format(len(seen)), 'red', attrs=['bold'])
for k,v in seen.items():
    cprint("{} : {}".format(k.rstrip(),v), 'green', attrs=['bold'])